### ISSUE TITLE
Taxjar attribute tj_ptc creates error when getting all options via magento core function

### ISSUE THREAD

**Issue by cypher909** [taxjar/taxjar-magento2-extension#181]
### Prerequisites

- [x] Are you running the latest version of our extension?
- [x] Have you reviewed our [integration guide](https://www.taxjar.com/guides/integrations/magento2/)?
- [x] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description

I have an extension that calls $attribute->getOptions() on the product attributes. When it calls getOptions() on attribute with code tj_ptc it throws the following error:

PHP Fatal error:  Uncaught Error: Call to a member function getAllOptions() on string in \magento\vendor\magento\module-eav\Model\Entity\Attribute\AbstractAttribute.php:1184

I believe this happens because the attribute is not created according to Magento standards. The function getOptions is a magento core function and is not specific to any third party extension. The error happens in Magento core when Magento itself calls method $attribute->getAllOptions() in \vendor\magento\module-eav\Model\Entity\Attribute\AbstractAttribute.php

### Steps to Reproduce

1. Create an extension that runs code like the following:
```
$attributes = $product->getAttributes();
foreach ($attributes as $attribute) {
    $options = $attribute->getOptions();
}
```

### Expected Result
Returns select options

### Actual Result
Throws error

### Versions

- [x] Magento 2.3

- [x] Magento Open Source (CE)

- [x] PHP 7.x

**Comment by sethobey** [comment]
Hi @cypher909,

Were you able to resolve this issue? I am unable to reproduce the behavior you describe.

I first attempted to recreate the issue by creating a controller action which would retrieve a product and call the code snippet you included above, but this did not result in an error, and I see the product's attributes displayed on the page.

Looking into the core code in `AbstractAttribute::getOptions()`, I saw the call to method `getAllOptions()` that you also mentioned above, so I replaced the call to `$attribute->getOptions();` with `$attribute->getSource()->getAllOptions();`, but again this did not produce an error.

If you are still experiencing the described error, please reopen this issue with any additional details that may help us to recreate this bug so that we may assist you!
