### ISSUE TITLE
Address Validation should not allow work for saved address in checkout page

### ISSUE THREAD

**Issue by rangerz** [taxjar/taxjar-magento2-extension#183]
### Prerequisites

- [x] Are you running the latest version of our extension?
- [x] Have you reviewed our [integration guide](https://www.taxjar.com/guides/integrations/magento2/)?
- [x] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description
Address validation work fine for guest in checkout page.
It also work fine in customer dashboard (Address Book Page) for Add New Address and and Edit Address.
But 
It's not work for saved address of login customers in checkout page.
If customer saved a not validation address in their address book for shipping address, in checkout page will appear suggested addresses section for `Suggest Address` radio. If selected the suggested address, it will not apply for shipping address of this order. (But work for billing address although the display is still the original address)

By the way, another issue is customer can add new address in checkout page. it's not work for address validation.

### Steps to Reproduce

1. Login customer and save a address that is not suggested
2. add to cart and. go to checkout page
3. **[Important] New Address in checkout page and select it.** 
3. Also select suggested address and place order
4. Into My Orders (/sales/order/history/) View Order to check address

![image](https://user-images.githubusercontent.com/3338473/117788521-131e3d80-b20d-11eb-99a6-41eb136a50de.png)

### Expected Result
- Suggest address can apply for shipping address and billing address and also display correctly.
- Hopefully it also can popup a confirm modal to edit saved address.
- Add address in checkout can support address validation

### Actual Result
- Not apply shipping address for suggest address
- Saved address is still not correct.
- Add address in checkout can't work for address validation.

### Versions

- [x] Magento 2.4
- [ ] Magento 2.3
- [ ] Magento 2.2
- [ ] Magento 2.1

- [ ] Magento Open Source (CE)
- [x] Magento Commerce (EE)
- [x] Magento B2B
- [x] Magento Cloud

- [x] PHP 7.x
- [ ] PHP 5.x

**Comment by rangerz** [comment]
Updated Steps to Reproduce part.
it needs "New Address" to trigger address suggestion. (It should be not happened I think)

**Comment by sethobey** [comment]
Hi @rangerz I know this issue has been outstanding for awhile, but taking a look now, it appears that possibly part of this issue has been resolved in various address-validation-related changes since the original issue report.

> If selected the suggested address, it will not apply for shipping address of this order. (But work for billing address although the display is still the original address)

As an existing user with a pre-existing non-validated address w/ only 5 digit zip code: Upon navigating to checkout, I observed that the "Suggested Address" block was rendered as expected with the suggested validated address having a 5+4 zip code format as expected rather than the 5 digit zip code on the existing address.

Upon selecting the suggested address, the selected Shipping address item's address does not change, but the change _IS_ reflected in the checkoutConfig state, which can be further validated by selecting the "Same as shipping address" option for billing address, where upon selection, the validated 5+4 zip code will be present on the billing address view.

> By the way, another issue is customer can add new address in checkout page. it's not work for address validation.

I also looked into this, and believe it to be resolved as well. As an existing user navigating to checkout with items in cart, I selected to add new address, and upon selecting from shipping address items, TaxJar address validation validated the new address which I was able to use for billing as well.

In light of the above discovery, I'm going to close this issue, but if you (or anyone reading) have updated to our latest release and are still experiencing address validation related issues, please feel free to re-open issue or reach out to our support via support@taxjar.com.

Thanks!
