### ISSUE TITLE
Unable to disconnect with Sandbox mode enabled

### ISSUE THREAD

**Issue by greezlu** [taxjar/taxjar-magento2-extension#337]
### Prerequisites

- [x] Are you running the latest version of our extension?
- [x] Have you reviewed our [integration guide](https://developers.taxjar.com/integrations/guides/magento2/)?
- [x] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Steps to Reproduce
1. Connect to TaxJar account.
2. Enter sandbox key.
3. Enable Sandbox mode.
4. Disconnect from TaxJar account.

### Expected Result
Successful disconnect with ability to connect.

### Actual Result
Account is disconnected. But **connect** button is not visible.
<details>
<summary>Screenshot</summary>
<img width="739" alt="bug" src="https://user-images.githubusercontent.com/28956720/188073704-cc9ebd81-8c68-4d82-b9ad-1f0b23c18581.png">
</details>

### Explanation
Problem appears here:
[Taxjar\SalesTax\Block\Adminhtml\Enabled::isConnected()](https://github.com/taxjar/taxjar-magento2-extension/blob/v1.9.9/Block/Adminhtml/Enabled.php#L124)

That method returns _bool_ depending on this answer:
[Taxjar\SalesTax\Model\Configuration::getApiKey()](https://github.com/taxjar/taxjar-magento2-extension/blob/v1.9.9/Model/Configuration.php#L105)

Method getApiKey() return sandbox key in case if Sandbox mode was enabled.

But Disconnect action is not removing Sandbox API key. **So main problem is here:**
[Taxjar\SalesTax\Controller\Adminhtml\Config\Disconnect::execute()](https://github.com/taxjar/taxjar-magento2-extension/blob/v1.9.9/Controller/Adminhtml/Config/Disconnect.php#L90)

Because Disconnect action class is not clearing Sandbox API key and not disabling Sandbox mode.
Please fix this. Thank you.

### Versions

- [x] Magento 2.4
- [x] Magento 2.3

- [x] Magento Open Source (fka Magento 2 Community Edition)
- [x] Adobe Commerce (fka Magento 2 Enterprise Edition)

- [x] PHP 8.2
- [x] PHP 8.1
- [x] PHP 7.4
- [x] PHP 7.3

**Comment by sethobey** [comment]
@greezlu Thank you for the detailed issue report! We will be sure to include a fix in the next release 👍

To anyone experiencing this issue, this error can be resolved by clearing the TaxJar sandbox API key value using the CLI command: `bin/magento config:set tax/taxjar/sandbox_apikey ''`

Edit: Will also require command `bin/magento config:set tax/taxjar/sandbox 0` to ensure Sandbox mode is not enabled, because although removing sandbox API key will resolve UI error, sandbox mode enabled will prevent re-connecting to TaxJar later.
