### ISSUE TITLE
Nexus Addresses Not Working

### ISSUE THREAD

**Issue by fredpope** [taxjar/taxjar-magento2-extension#39]
Clicking on the Nexus Addresses reveals a blank page.

**Comment by ryanreeves-taxjar** [comment]
Thanks for letting us know about this @fredpope.  We're taking a look into the issue and will let you know as we have more details!

**Comment by dankoz51** [comment]
We have the same issue, nothing on the screen and i cant find anything in the logs

**Comment by ryanreeves-taxjar** [comment]
Thanks @dankoz51.  Could you try these steps from this thread and let me know if that solves your problem?  

https://github.com/taxjar/taxjar-magento2-extension/issues/38#issuecomment-438762744

If you're still having trouble, please feel free to reach out to our support team at support@taxjar.com so we can respond to you directly.  Thanks!

**Comment by ryanreeves-taxjar** [comment]
Hi @dankoz51 and @fredpope,

I wanted to check-in and see if you're still experiencing this issue.  Thanks!

**Comment by dankoz51** [comment]
stil having the issue

**Comment by ryanreeves-taxjar** [comment]
Thanks @dankoz51.  Because we're unable to reproduce this issue on a vanilla installation of Magento, could you email our support team at [support@taxjar.com](mailto:support@taxjar.com)?  Please mention this issue in the email and we will continue with more in depth troubleshooting.

**Comment by dankoz51** [comment]
I finally tracked this down this issue is that as of magento 2.2 there is not more admin feature to disable module output.  Yet there were still entries in the core_config_data table. The code still disabled the output for the static content publishing. 

So removing 
advanced/modules_disable_output/Taxjar_SalesTax  = 1 
from the core config data table solved the issue
