### ISSUE TITLE
No way to set products as fully taxable

### ISSUE THREAD

**Issue by marshallthornton** [taxjar/taxjar-magento2-extension#41]
According to the [API reference](https://developers.taxjar.com/api/reference/#categories) for categories, if you want to tax the item as fully taxable without any special category adjustments you should send no "product_tax_code" for that line item. This module does not seem to support this since #10 now causes "None" to send the fully exempt tax code and selecting a different category can cause unintended tax issues in any state that has special rules around it.

There should probably be another category added that is labeled "Fully Taxable" to match what is in the API reference that will blank out the tax code for the line item that people can use for items that don't fall into any of the other categories.

**Comment by ryanreeves-taxjar** [comment]
Thanks for taking the time to report this issue @marshallthornton.  We're hoping to prioritize a fix for this and will get a release pushed soon.

**Comment by fastdivision** [comment]
Fixed in #51 to rename "None" to "Fully Taxable" when assigning a product tax class to a TaxJar product category. #10 addresses a different issue with not setting a product tax class at all on a product. When reviewing both tax classes on products and the underlying TaxJar categories on tax classes, this update should reduce confusion.
